### ISSUE TITLE
bug when location is null.

### ISSUE THREAD

**Issue by nqd** [lunchifyvn/lunchify#64]
```
  1) User select API should allow user to get the suggestion:
     Uncaught TypeError: Cannot read property 'lat' of undefined
      at distanceBetween2Locations (lib/matching.js:75:46)
      at distanceBetween2Users (lib/matching.js:68:10)
      at _.reduce (lib/matching.js:28:20)
      at Function._.reduce._.foldl._.inject (node_modules/underscore/underscore.js:145:14)
      at filterByDistance (lib/matching.js:27:12)
      at Object.matchProfile (lib/matching.js:21:25)
      at User.find (common/models/user.js:23:35)
```

@lenguyenthanh could you plz handle this? Check for not existing before get its value

**Comment by lenguyenthanh** [comment]
Ok, matched list will be empty if location is null
